version: '2'
services:
  app1:
    image: nicopaez/password-api:latest
    ports:
      - "3001:3000"
  app2:
    image: nicopaez/password-api:latest
    ports:
      - "3002:3000"
  nginx:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2